Jenkinsfile (Declarative Pipeline)
/* Requires the Docker Pipeline plugin */
pipeline {
    agent { docker { image 'maven:3.9.0-eclipse-temurin-11' } }
    stages {
        stage('docker up') {
            steps {
                sh 'docker-compose -f app/docker-compose.yml up --build --force-recreate -d'
            }
        }
    }
}
